### ISSUE TITLE
动画

### ISSUE THREAD

**Issue by xiongshj** [xiongshj/blog#20]
# 动画

*这是学习《CSS 权威指南》第 18 章的笔记。*

## `@keyframes` 规则

使用 `@keyframes` 规则定义可复用的 CSS 关键帧动画，并为动画起个名称。然后，通过这个名称把对应的动画效果应用到元素或伪元素上。

一个 `@keyframes` 规则有一个动画标识符（即动画的名称），以及一个到多个关键帧块。每个关键帧块有一个到多个关键帧选择符，声明属性及其值。整个 `@keyframes` 规则设置一个动画效果的完整迭代过程。

关键帧选择符可以是以逗号分隔的一组百分数，也可以是关键字 from 或 to。关键字 from 等于 0%，to 等于 100%。

```CSS
@keyframes fadeout {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

@keyframes color-pop {
  0% {
    color: black;
    background-color: white;
  }
  33% {
    color: gray;
    background-color: yellow;
  }
  100% {
    color: white;
    background-color: orange;
  }
}
```

## 把动画应用到元素上

定义好关键帧动画便可以把动画应用到元素和伪元素上。为了把动画附加到元素上，并控制动画的播放过程，CSS 提供了多个相关的属性。若想保证动画效果能显示出来，至少要指明动画的名称，以及持续时间（不然动画瞬间就结束了）。

### animation-name 属性

animation-name 属性的值为一个逗号分隔的列表，指定想应用的关键帧动画的名称。这里所说的名称是指使用 `@keyframes` 规则定义动画时设定的无引号标识符或有引号的字符串。

animation-name 属性默认值为 none，表示没有动画效果。如果想应用动画，把值设为 `@keyframes` 的标识符，即动画的名称。

```CSS
div {
  animation-name: fadeout;
}
```

这个规则把 fadeout 动画应用到所有 div 元素上。

如果想应用多个动画，以逗号分开多个 `@keyframes` 标识符。

```CSS
div {
  animation-name: fadeout, color-pop;
}
```

如果指定的一系列关键帧标识符中有一个不存在，不会导致所有动画都无法应用，只是那个不存在的动画被忽略，其他有效的动画仍将应用。

### animation-duration 属性

animation-duration 属性定义动画迭代一次用时多久，单位为秒（s）或毫秒（ms），初始值是 0s。

如果不声明 animation-duration，动画仍将播放，只不过持续时间为 0s，看不到实际效果，而且 animationstart 和 animationend 事件也会触发。这个属性的值不能为负数。

如果一组以逗号分隔的持续时间中有无效的值，整个声明都失效。

### animation-iteration-count 属性

只声明必须的 animation-name 属性，动画将播放一次，而且只播放一次。如果希望迭代的次数不是默认的一次，使用 animation-iteration-count 属性设定。

animation-iteration-count 属性不允许设为负值，如果提供的值无效，将重置为默认值 1，只迭代一次。

有趣的是，0 是 animation-iteration-count 属性的有效值。设为 0 时，动画依然播放，只不过迭代零次。与 `animation-duration: 0s;` 类似，这也会触发 animationstart 和 animationend 事件。这个属性的值也可以不是整数。

### animation-direction 属性

使用 animation-direction 属性可以控制动画是从 0% 关键帧向 100% 关键帧播放，还是从 100% 关键帧向 0% 关键帧播放。可以让所有迭代都按照相同的方向播放，也可以隔一个循环变换一次方向。

animation-direction 属性定义按什么方向播放动画的关键帧。可取的值有四个：

（1）`animation-direction: normal;`

设为 normal 时（或者省略，默认为 normal），动画的每次迭代都会从 0% 关键帧向 100% 关键帧播放。

（2）`animation-direction: reverse;`

reverse 值逆序播放各次迭代，即从 100% 关键帧向 0% 关键帧播放。逆转动画的方向也就逆转了 animation-timing-function。

（3）`animation-direction: alternate;`

alternate 值的意思是第一次迭代（以及后续各奇数次迭代）从 0% 向 100% 播放，第二次迭代（以及后续各偶数次迭代）方向相反，从 100% 向 0% 播放。

（4）`animation-direction: alternate-reverse;`

alternate-reverse 值与 alternate 值类似，只不过是反过来的。第一次迭代（以及后续各奇数次迭代）从 100% 向 0% 播放，第二次迭代（以及后续各偶数次迭代）方向相反，从 0% 向 100% 播放。

### animation-delay 属性

animation-delay 属性设定把动画附加到元素上之后隔多久开始播放动画，单位为秒（s）或毫秒（ms），初始值是 0s。

如果设为负值，动画立即开始播放，不过是从动画的中途开始。

利用 animation-delay 属性把多个动画串在一起，让下一个动画在前一个动画结束后立即开始：

```CSS
.rainbow {
  animation-name: red, orange, yellow, blue, green;
  animation-duration: 1s, 3s, 5s, 7s, 11s;
  animation-delay: 3s, 4s, 7s, 12s, 19s;
}
```

后续各动画都在前一个动画结束后开始。我们称这样的效果为 CSS 动画链。

### animation-timing-function 属性

animation-timing-function 属性指明动画在一次循环（或迭代）中如何演进，初始值是 ease。

可以取的值有 ease、ease-in、ease-out、ease-in-out、linear 等。

### animation-play-state 属性

使用 animation-play-state 属性定义动画是播放还是暂停的。

设为默认值 running 时，动画正常播放。设为 paused 时，动画暂停。

### animation-fill-mode 属性

animation-fill-mode 属性定义动画播放结束后是否应用原来的属性值。

这个属性可以取的值有四个：none、forwards、backwards 和 both，初始值是 none。

### animation 简写属性

使用 animation 简写属性，无需分别定义 8 个属性，在一行声明中就能为元素定义全部动画属性。

初始值是 0s ease 0s 1 normal none running none。

在 animation 简写属性中，无需声明所有值；未声明的值将被设为默认值（初始值）。

各单独属性的初始值（默认值）如下：

```CSS
#animation {
  animation-name: none;
  animation-duration: 0s;
  animation-timing-function: ease;
  animation-delay: 0s;
  animation-iteration-count: 1;
  animation-fill-mode: none;
  animation-direction: normal;
  animation-play-state: running;
}
```

简写属性中有些值的顺序是重要的。其一，有两个时间相关的属性，如果列出两个时间值，第一个始终为持续时间，第二个是延迟时间。其二，建议把 animation-name 属性的值放在最后。

## 其他

与动画有关的三个事件：animationstart、animationend 和 animationiteration。

2017 年年末，浏览器新增了一个媒体查询：prefers-reduced-motion。创作人员可以通过这个媒体查询为浏览器或其他设备中设置了“减少运动效果”或类似偏好设置的用户定义样式。强烈建议像下面这样做：

```CSS
@media (prefers-reduced-motion) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
```

这个规则禁用全部动画和过渡。反过来，我们可以把所有动画和过渡单独放在一处，针对没有启用“减少运动效果”的用户：

```CSS
@media not (prefers-reduced-motion) {
  /* 所有动画和过渡 */
}
```

## 小结

心里有光，哪儿都美。
