### ISSUE TITLE
盒尺寸四大家族

### ISSUE THREAD

**Issue by xiongshj** [xiongshj/blog#26]
# 盒尺寸四大家族

*这是学习《CSS 世界》第 4 章的笔记。*

## 深入理解 content

根据“外在盒子”是内联还是块级我们可以把元素分为内联元素和块级元素，而根据是否具有可替换内容，我们也可以把元素分为替换元素和非替换元素。

替换元素，内容可以被替换。例如 `<img>`。

`<img>` 和其他一些替换元素的替换内容的适配方式可以通过 `object-fit` 属性修改了。

`<span>` 标签设置 width 和 height 是无效的。

在 Chrome 浏览器下，所有的元素都支持 content 属性，而其他浏览器仅在 `::before`/`::after` 伪元素中才有支持。

在 CSS 世界中，我们把 content 属性生成的对象称为“匿名替换元素“。

content 属性生成的内容和普通元素内容会有很多不同的特性表现：使用 content 生成的文本是无法选中、无法复制的，好像设置了 `user-select: none` 声明一般，但是普通元素的文本却可以被轻松选中，同时 content 生成的文本无法被屏幕阅读设备读取，也无法被搜索引擎抓取；不能左右 `:empty` 伪类等。

在实际项目中，content 属性几乎都是用在 `::before`/`::after` 这两个伪元素中，因此，“content 内容生成技术”有时候也称为“::before/::after 伪元素技术”。

IE8 浏览器仅支持单冒号的伪元素。

## 温和的 padding 属性

一个错误的认知：内联元素的 padding 只会影响水平方向，不会影响垂直方向。

内联元素 padding 对视觉层和布局层具有双重影响，所有类似“垂直方向 padding 对内联元素没有作用”的说法显然是不正确的。

利用内联元素的 padding 实现高度可控的分隔线([链接](https://demo.cssworld.cn/4/2-2.php))：
````HTML
<a href="">登录</a><a href="">注册</a>
````
````CSS
a + a:before {
  content: "",
  font-size: 0;
  padding: 10px 3px 1px;
  margin-left: 6px;
  border-left: 1px solid gray;
}
````

网页可以通过地址栏的 hash 值和页面 HTML 中 id 值一样的元素发生锚点定位。

padding 属性是不支持负值的。

padding 支持百分比值，padding 百分比值无论是水平方向还是垂直方向均是相对于宽度计算的。

````CSS
/* 实现一个正方形 */
div {
  padding: 50%;
}

/* 实现一个宽高比为 2:1 的矩形 */
div {
  padding: 25% 50%;
}

/* 实现一个宽高比为 5:1 的比例固定的头图效果 */
.box {
  position: relative;
  padding: 10% 50%;
}

.box > img {
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
}
````

CSS 实现“三道杠”图标效果：

````HTML
<i class="icon-menu"></i>
````

````CSS
.icon-menu {
  display: inline-block;
  width: 14px;
  height: 1px;
  padding: 3.5px 0;
  border-top: 1px solid;
  border-bottom: 1px solid;
  background-color: red;
  background-clip: content-box;
}
````

## 激进的 margin 属性

左侧定宽，右边自适应的两栏布局效果：
````CSS
.box {
  overflow: hidden;
}

.box > img {
  float: left;
}

.box > p {
  margin-left: 140px;
}
````

````HTML
<div class="box">
  <img src="1.jpg">
  <p>文字内容...</p>
</div>
````

利用 margin 外部尺寸实现等高布局(块状元素)：
````CSS
.column-box {
  overflow: hidden;
}

.column-left,
.column-right {
  margin-bottom: -9999px;
  padding-bottom: 9999px; // 可以使用 border-bottom: 9999px solid transparent 代替
}
````

内联元素垂直方向的 margin 是没有任何影响的，既不会影响外部尺寸，也不会影响内部尺寸。

和 padding 属性一样，margin 的百分比值无论是水平方向还是垂直方向都是相对于宽度计算的。

块级元素的上外边距与下外边距有时会合并为单个外边距，这样的现象称为“margin 合并”。

margin 合并的3种场景：
- 相邻兄弟元素 margin 合并。
- 父级和第一个/最后一个子元素。
- 空块级元素的 margin 合并。

`margin: auto` 的填充规则如下:
- 如果一侧定值,一侧 auto，则 auto 为剩余空间大小。
- 如果两侧均是 auto，则平分剩余空间。

margin 默认值是 0。

如果想让某个块状元素右对齐，脑子里不要就一个 `float: right`，很多时候，`margin-left: auto` 才是最佳的实践，浮动毕竟是个“小魔鬼”。

绝对定位元素的 margin: auto 居中：
````CSS
.father {
  position: relative;
  width: 300px;
  height: 150px;
}

.son {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  width: 200px;
  height: 100px;
  margin: 0;
}
````

## 功勋卓越的 border 属性

CSS 世界中很多大受欢迎的属性之所以受欢迎，并不是因为其本职工作做得很好，而是衍生出来的特性可以用来解决很多棘手的问题。border 属性就是典型代表之一。

虽然同属于盒模型基本成员，但是 border-width 却不支持百分比。

我们平常使用 border-width 几乎全是固定的数值，如 border-width: 1px 之类，但是，可能有些人并不知道 border-width还支持若干关键字，包括 thin、medium(默认值) 和 thick，对应的尺寸大小具体如下：
- thin：薄薄的，等同于 1px。
- medium(默认值)：薄厚均匀，等同于 3px。
- thick：厚厚的，等同于 4px。

为什么 border 属性的默认宽度大小是 medium，也就是 3px，明明 thin(1px) 宽度更常用吧？为什么呢？因为 border-style: double 至少 3px 才有效果。

各种 border-style 类型：
- border-style 的默认值是 none。
- border-style: solid 实线边框。
- border-style: dashed 虚线边框。
- border-style: dotted 虚点边框。在 Chrome 以及 Firefox 浏览器下虚点实际上是个小方点，而 IE 浏览器下则是小圆点。
- border-style: double 双线边框，顾名思义，即两根线且为实线。
- 其他 border-style 类型：inset(内凹)、outset(外凸)、groove(沟槽)、ridge(山脊)，兼容性不好，基本不使用。

border-color 默认颜色就是 color 色值，就是当没有指定 border-color 颜色值的时候，会使用当前元素的 color 计算值作为边框色。具有类似特性的 CSS 属性还有 outline、box-shadow 和 text-shadow 等。

上传图片带有加号的框框按钮 [链接](https://demo.cssworld.cn/4/4-1.php)。

使用透明 border 增加点击区域：
````CSS
.icon-clear {
  width: 16px;
  height: 16px;
  border: 11px solid transparent;
}
````

使用 border 属性绘制三角形：
````CSS
div {
  width: 0;
  border: 10px solid;
  border-color: #f30 transparent transparent;
}
````

border 等高布局技术 [链接](https://demo.cssworld.cn/4/4-4.php)。

## 小结

脚踏实地，仰望星空。
